services:
    web:
        build: .
        env_file:
            - ./api/.env
        ports:
            - "8010:8010"
        depends_on:
            - db
        volumes:
            - .:/app:rw
        command: python manage.py runserver 0.0.0.0:8010
